### ISSUE TITLE
error al compilar

### ISSUE THREAD

**Issue by camilo1993** [camilo1993/JAVA-8-Fundamentos#1]
probé de varias formas y me sale el siguiente error
![screenshot_1](https://user-images.githubusercontent.com/35336281/36006112-d2b9c5a2-0d19-11e8-91fd-7d78732ba76d.png)

**Comment by ggarcesv** [comment]
La sintaxis esta correcta es problema de configuración del proyecto, intenta creando un proyecto con un nombre corto.

**Directorio definido por nosotros para ordenar los temas**
/clase03-ejecutar un programa Java/

**Directorio del proyecto**
/clase03-ejecutar un programa Java/**Ejecutar Programa Java**/


Intenta con un nombre corto
/clase03-ejecutar un programa Java/**Ejecutar**/



, si te fijas creaste el proyecto llamado "Ejecutar Programa Java/

**Comment by camilo1993** [comment]
Ahora me resulto, voy a editar y lo subo.

**Comment by ggarcesv** [comment]
Ok, cerrare el issue
